//login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const ITEMS = "ITEMS";
export const ITEMS_ERROR = "ITEMS_ERROR";
export const SHARED_ITEMS = "SHARED_ITEMS";
export const SHARE_ITEM_SUCCESS = "SHARE_ITEM_SUCCESS";
export const SHARE_ITEM_FAILED = "SHARE_ITEM_FAILED";
export const REQUESTED_SHARED_ITEMS = "REQUESTED_SHARED_ITEMS";
export const TO_CONFIRM_SHARED_ITEMS = "TO_CONFIRM_SHARED_ITEMS";
export const GET_USER = "GET_USER";
